// Generated by Pelican from the endpoint descriptions of
// Screening 0.1.0. Do not edit: regenerate.
//
// Every method below is one endpoint value read a fourth way: the path,
// the parameter names and the payload types are the ones the server routes
// and the document publishes.
//
// Needs pelican-core on the classpath, a Codecs to read bodies with, and
// a ClientTransport to send with — pelican-client-pekko, unless you have
// an HTTP client of your own to hand over.
@file:Suppress("unused", "RedundantVisibilityModifier")

package bank.api.screening

import io.github.matthewjones372.pelican.BodyCodec
import io.github.matthewjones372.pelican.ClientRequest
import io.github.matthewjones372.pelican.ClientResponse
import io.github.matthewjones372.pelican.ClientTransport
import io.github.matthewjones372.pelican.Codecs
import io.github.matthewjones372.pelican.Method
import io.github.matthewjones372.pelican.UploadedFile
import io.github.matthewjones372.pelican.formCodec
import java.io.BufferedReader
import java.io.ByteArrayInputStream
import java.io.InputStream
import java.io.Reader
import java.io.SequenceInputStream
import java.net.URLEncoder
import java.nio.charset.StandardCharsets
import java.time.Duration
import java.util.Collections
import java.util.Enumeration
import java.util.UUID
import java.util.concurrent.CompletionException
import kotlin.reflect.typeOf

// ------------------------------------------------------------------ runtime
//
// Fixed. Nothing here depends on a particular API — only on how Pelican frames
// its responses, which is the same for every endpoint.

/**
 * A response this client cannot turn into a value: a status the endpoint never
 * declared, or a body its codec could not read. [cause] is the codec's own
 * failure in the second case and null in the first.
 */
class ApiCallFailed(
    val status: Int,
    val method: String,
    val path: String,
    body: String,
    cause: Throwable? = null,
) : RuntimeException("$method $path -> $status: ${body.take(MESSAGE_BODY_CHARS)}", cause) {

    /**
     * What arrived, up to the cap. A proxy's error page is as long as the proxy
     * cares to make it, and this is held for as long as something holds the
     * failure.
     */
    val body: String =
        if (body.length <= MAX_BODY_CHARS) body
        else body.take(MAX_BODY_CHARS) + "… (truncated; ${body.length} characters in all)"
}

/** Eight KiB of it, which is enough of a gateway's HTML to recognise it by. */
private const val MAX_BODY_CHARS = 8 * 1024

/** Less again in the message, which is the part that reaches a log line. */
private const val MESSAGE_BODY_CHARS = 500

/**
 * A call that either succeeded or came back as one of the failures its endpoint
 * declared.
 *
 * The failure side is a sealed type generated per endpoint, so a `when` over it
 * is exhaustive: add a failure to the endpoint, regenerate, and the calls that
 * do not handle it stop compiling.
 */
sealed interface Outcome<out F, out T> {
    data class Ok<T>(val value: T) : Outcome<Nothing, T>
    data class Err<F>(val failure: F) : Outcome<F, Nothing>
}

/** The success value, or null if the call came back as a declared failure. */
fun <F, T> Outcome<F, T>.valueOrNull(): T? = (this as? Outcome.Ok)?.value

/** The success value, or [ApiCallFailed] carrying the failure that arrived instead. */
fun <F, T> Outcome<F, T>.orThrow(): T = when (this) {
    is Outcome.Ok -> value
    is Outcome.Err -> throw IllegalStateException("Call failed: $failure")
}

/**
 * A response read whole.
 *
 * Every call but a streaming one needs its body as text, and needs it after it
 * has looked at the status: a declared failure decodes the body, and so does
 * the throw for a status nothing declared. Reading it once, here, is what stops
 * those two from being a first reader and an empty stream.
 */
class TextResponse internal constructor(
    private val response: ClientResponse,
    /** The whole body, decoded as UTF-8. */
    val body: String,
) {
    val status: Int get() = response.status

    /**
     * One header off the response, as the string it travelled as. Null when it
     * was not sent — which the declared failures below carry through, rather
     * than insisting on a header the server may have had nothing to say about.
     */
    fun header(name: String): String? = response.header(name)
}

/**
 * A response read as it arrives, rather than after it has all arrived.
 *
 * Iterating to the end closes the connection. Stopping early does not, so a
 * caller who might stop early should `use` it:
 *
 * ```
 * client.listOrders(1L, limit = 100).use { orders ->
 *     orders.first { it.status == OrderStatus.SHIPPED }
 * }
 * ```
 */
class Streamed<T> internal constructor(
    private val body: InputStream,
    private val elements: Sequence<T>,
    private val ids: EventIds = EventIds(),
) : Sequence<T>, AutoCloseable {

    /**
     * The `id:` of the most recent event handed over, to reconnect from where
     * this stream stopped — pass it back as the call's `lastEventId`. Null
     * before the first one arrives, and on a stream that sends no ids at all.
     */
    val lastEventId: String? get() = ids.last

    private var iterated = false

    override fun iterator(): Iterator<T> {
        check(!iterated) { "A streamed response can only be read once" }
        iterated = true
        val underlying = elements.iterator()
        return object : Iterator<T> {
            override fun hasNext(): Boolean = underlying.hasNext().also { if (!it) close() }
            override fun next(): T = underlying.next()
        }
    }

    override fun close() = body.close()
}

/** Newline-delimited JSON: one document per line. */
internal fun ndjsonFrames(reader: BufferedReader): Sequence<String> =
    reader.lineSequence().filter { it.isNotBlank() }

/**
 * A sequence of values as a newline-delimited request body.
 *
 * One stream per frame, chained lazily, so a value is encoded when the
 * transport asks for it rather than when the call is made — the upload is
 * pulled at the speed the socket drains it, and nothing holds the whole of it.
 *
 * The sequence is iterated inside `open()`, so a transport that has to send the
 * request again asks the sequence for its elements again. One that cannot
 * supply them twice — a sequence over a live cursor — is a body that must not
 * be retried, which is the caller's own knowledge to act on.
 */
internal fun <T> ndjsonBody(values: Sequence<T>, encode: (T) -> String): ClientRequest.Body =
    ClientRequest.Body.Streaming {
        val frames = values.iterator()
        SequenceInputStream(
            object : Enumeration<InputStream> {
                override fun hasMoreElements(): Boolean = frames.hasNext()

                override fun nextElement(): InputStream =
                    ByteArrayInputStream((encode(frames.next()) + "\n").toByteArray(StandardCharsets.UTF_8))
            },
        )
    }

/**
 * Where a stream that sends ids has reached. Written by the frame reader and
 * read through [Streamed.lastEventId]; separate from both so the sequence can
 * report progress to a response it is being read out of.
 */
internal class EventIds {
    var last: String? = null
}

/**
 * An event stream read as values, keeping the id of the last one delivered.
 * The reader and the id it fills in are made together, so a caller of the
 * generated method has nothing to wire up.
 */
internal fun <T> sseStreamed(body: InputStream, decode: (String) -> T): Streamed<T> {
    val ids = EventIds()
    return Streamed(body, sseFrames(body.bufferedReader(), ids).map(decode), ids)
}

/**
 * Server-sent events. A frame's payload may be split across several `data:`
 * lines, rejoined with newlines here — the same rule the server framed them by.
 *
 * An `id:` is recorded as its own frame is handed over, so the id a caller
 * reads is the one belonging to the event it is holding. A frame carrying none
 * leaves the previous id standing, which is what the SSE specification says the
 * last event id does.
 */
internal fun sseFrames(reader: BufferedReader, ids: EventIds = EventIds()): Sequence<String> = sequence {
    val data = mutableListOf<String>()
    var id: String? = null
    for (raw in reader.lineSequence()) {
        val line = raw.removeSuffix("\r")
        when {
            line.isEmpty() -> if (data.isNotEmpty()) {
                id?.let { ids.last = it }
                yield(data.joinToString("\n"))
                data.clear()
                id = null
            }

            line.startsWith(":") -> Unit // comment, typically a keep-alive
            line.startsWith("id:") -> id = line.removePrefix("id:").removePrefix(" ")
            line.startsWith("data:") -> data += line.removePrefix("data:").removePrefix(" ")
        }
    }
    if (data.isNotEmpty()) {
        id?.let { ids.last = it }
        yield(data.joinToString("\n"))
    }
}

/**
 * A JSON array, element by element.
 *
 * Decoding the whole body at once would defeat the point of the server having
 * flushed the elements as it produced them, so this splits the array at
 * top-level commas — tracking string and escape state, which is the only way a
 * comma can be part of an element rather than between two — and hands each
 * element to the codec on its own.
 */
internal fun jsonArrayFrames(reader: Reader): Sequence<String> = sequence {
    var started = false
    var depth = 0
    var inString = false
    var escaped = false
    val element = StringBuilder()

    while (true) {
        val read = reader.read()
        if (read < 0) break
        val ch = read.toChar()

        if (!started) {
            when {
                ch == '[' -> started = true
                ch.isWhitespace() -> Unit
                else -> error("Expected a JSON array, found '$ch'")
            }
            continue
        }

        if (inString) {
            element.append(ch)
            when {
                escaped -> escaped = false
                ch == '\\' -> escaped = true
                ch == '"' -> inString = false
            }
            continue
        }

        when {
            ch == '"' -> { inString = true; element.append(ch) }
            ch == '[' || ch == '{' -> { depth++; element.append(ch) }
            ch == '}' || (ch == ']' && depth > 0) -> { depth--; element.append(ch) }
            ch == ']' -> {
                if (element.isNotBlank()) yield(element.toString())
                return@sequence
            }

            ch == ',' && depth == 0 -> {
                if (element.isNotBlank()) yield(element.toString())
                element.setLength(0)
            }

            else -> element.append(ch)
        }
    }
    if (element.isNotBlank()) yield(element.toString())
}

/**
 * A `multipart/form-data` body, and the content type naming its boundary.
 *
 * The two travel together because a boundary that reached the body and not the
 * header would produce a request no server can read, and there is no reason for
 * a caller to be able to make that mistake.
 */
class MultipartContent internal constructor(
    internal val body: ClientRequest.Body,
    internal val contentType: String,
)

/**
 * Builds the envelope without holding a file in memory.
 *
 * The parts are chained as streams and handed over as a streaming body, so an
 * upload is read from wherever it lives at the speed the transport drains it —
 * the same promise the server makes when it hands a file part to a handler
 * unread.
 *
 * The parts arrive here already in the order a server reads them — everything
 * it reads as it arrives, and then the streamed part it stops at — because that
 * order is a property of the description and the generator reads it off there.
 * Nothing goes back for a field that followed the streamed part.
 *
 * The boundary is random per call rather than fixed. Streaming means the
 * content cannot be scanned for a clash beforehand, so the answer is a
 * delimiter no content will contain by accident.
 */
internal fun multipart(
    fields: List<Pair<String, Any?>>,
    files: List<Pair<String, UploadedFile?>>,
): MultipartContent {
    val boundary = "PelicanBoundary" + UUID.randomUUID().toString().replace("-", "")
    val parts = mutableListOf<InputStream>()

    fields.forEach { (name, value) ->
        val text = plain(value) ?: return@forEach
        parts += ascii("--$boundary\r\nContent-Disposition: form-data; name=\"$name\"\r\n\r\n")
        parts += ByteArrayInputStream(text.toByteArray(StandardCharsets.UTF_8))
        parts += ascii("\r\n")
    }

    files.forEach { (name, file) ->
        if (file == null) return@forEach
        val disposition = StringBuilder("--$boundary\r\nContent-Disposition: form-data; name=\"$name\"")
        file.filename?.let { disposition.append("; filename=\"").append(it).append('"') }
        disposition.append("\r\nContent-Type: ").append(file.contentType ?: "application/octet-stream")
        disposition.append("\r\n\r\n")
        parts += ascii(disposition.toString())
        parts += file.stream()
        parts += ascii("\r\n")
    }

    parts += ascii("--$boundary--\r\n")

    val body = SequenceInputStream(Collections.enumeration(parts))
    return MultipartContent(
        ClientRequest.Body.Streaming { body },
        "multipart/form-data; boundary=$boundary",
    )
}

private fun ascii(text: String): InputStream =
    ByteArrayInputStream(text.toByteArray(StandardCharsets.ISO_8859_1))

/** A path, query or header value as the string it travels as. */
private fun plain(value: Any?): String? = when (value) {
    null -> null
    is Enum<*> -> value.name
    else -> value.toString()
}

/**
 * How many times one query parameter or cookie appears on the wire: not at
 * all when it was left out, once when it carries a value, and once per element
 * when it was declared as a repeated list.
 */
private fun occurrences(name: String, value: Any?): List<String> = when (value) {
    null -> emptyList()
    is Collection<*> -> value.mapNotNull { plain(it) }.onEach { element(name, it) }
    else -> listOfNotNull(plain(value))
}

/**
 * A list that travels as one occurrence, joined by the separator its
 * declaration named. Null for an absent parameter and for an empty list
 * alike: neither has anything to say, and `tags=` is not a shorter way of
 * saying nothing.
 */
private fun joined(name: String, values: Collection<*>?, separator: String): String? =
    values?.mapNotNull { plain(it) }?.onEach { element(name, it) }
        ?.takeIf { it.isNotEmpty() }?.joinToString(separator)

/**
 * One element of a list, checked before it is written.
 *
 * A server reads an occurrence carrying nothing as no element at all — that is
 * what makes `?tags=` mean "a field nobody filled in" — so an empty element
 * would arrive as a list one shorter than the one that was passed, with
 * nothing on either side able to tell. Refused here, where the caller still
 * has the list in hand.
 */
private fun element(name: String, value: String) {
    require(value.isNotEmpty()) {
        "'$name' was given an element that carries nothing, and an occurrence carrying nothing is not " +
            "an element — it would not arrive. Leave it out of the list."
    }
}

private fun urlEncode(value: String): String = URLEncoder.encode(value, StandardCharsets.UTF_8)

/** Path segments are encoded more conservatively than query values. */
private fun segment(value: Any?): String = urlEncode(plain(value) ?: "").replace("+", "%20")

// ---------------------------------------------------------------- payloads

data class Amount(
    val value: String,
    val currency: String,
)

data class ProposedTransfer(
    val transfer: String,
    val from: String,
    val to: String,
    val amount: Amount,
    val requestedAtMillis: Long,
)

data class Decision(
    val outcome: String,
    val rule: String? = null,
    val version: Int? = null,
    val evidence: String,
)

// ------------------------------------------------------------------ client

private const val DEFAULT_BASE_URL = ""

class ScreeningClient(
    baseUrl: String = DEFAULT_BASE_URL,
    private val codecs: Codecs,
    /**
     * Where a built request goes. The default is whichever `ClientTransport`
     * the classpath supplies — `pelican-client-pekko`, over Pekko HTTP's
     * client, unless the build says otherwise — so a service that already
     * runs and tunes an HTTP client can hand that one over rather than acquire
     * a second HTTP stack because it generated a client.
     */
    private val transport: ClientTransport = ClientTransport.default(),
    private val timeout: Duration = Duration.ofSeconds(30),
    /**
     * Sent with every request. A function rather than a map because it is
     * called per request, which is what a short-lived token needs.
     */
    private val headers: () -> Map<String, String> = { emptyMap() },
) {

    /** Where this client's calls go, unless an operation named a server of its own. */
    private val base: String = baseUrl.trimEnd('/')

    init {
        require(base.isNotEmpty()) {
            "This client has no base URL: the spec it was generated from declared no server. " +
                "Pass one: ${this::class.simpleName}(baseUrl = \"https://...\", codecs = ...)"
        }
    }

    /**
     * Every call goes through here. An absent query parameter or header is left
     * off rather than sent empty, so the server applies its own default.
     *
     * What comes out is a `ClientRequest`, which is core's own vocabulary rather
     * than any HTTP library's: the URL is assembled and encoded here, where the
     * description is, and the transport is left with nothing to decide.
     *
     * [origin] is this client's own base URL, except for a method the document said
     * is served somewhere else: those pass the host that operation's `servers`
     * block named, since that is where the service answers it. A webhook passes the
     * subscriber's URL, which nothing in the document could have known.
     *
     * [standingHeaders] defaults to the ones this client sends with everything —
     * and a webhook passes none, because those are the credential the client
     * presents to the API and a subscriber's endpoint is not the API.
     *
     * [deadline] is this client's own, except for a call that streams: those pass
     * null. A deadline is for a call that ends, and the three transports do not
     * bound the same thing — Ktor's request timeout ends the whole exchange, the
     * reading of the body included, while the JDK's and Pekko's are done once the
     * response head arrives. A stream inheriting it therefore died at the deadline
     * on one transport and ran on the other two.
     */
    private fun request(
        method: Method,
        path: String,
        query: List<Pair<String, Any?>> = emptyList(),
        headerParams: List<Pair<String, Any?>> = emptyList(),
        cookies: List<Pair<String, Any?>> = emptyList(),
        body: ClientRequest.Body = ClientRequest.Body.Empty,
        contentType: String? = null,
        multipart: MultipartContent? = null,
        origin: String = base,
        standingHeaders: Map<String, String> = headers(),
        deadline: Duration? = timeout,
    ): ClientRequest {
        val search = query
            .flatMap { (name, value) -> occurrences(name, value).map { "${urlEncode(name)}=${urlEncode(it)}" } }
            .joinToString("&")

        // One header carries all of them, so an absent optional cookie is simply
        // not written rather than sent empty — the same bargain every other
        // optional parameter makes.
        val jar = cookies.flatMap { (name, value) -> occurrences(name, value).map { "$name=$it" } }

        val sent =
            listOfNotNull((multipart?.contentType ?: contentType)?.let { "Content-Type" to it }) +
                standingHeaders.map { (name, value) -> name to value } +
                headerParams.mapNotNull { (name, value) -> plain(value)?.let { name to it } } +
                (if (jar.isEmpty()) emptyList() else listOf("Cookie" to jar.joinToString("; ")))

        return ClientRequest(
            method = method,
            url = origin + path + if (search.isEmpty()) "" else "?$search",
            headers = sent,
            body = multipart?.body ?: body,
        ).withTimeout(deadline)
    }

    private fun TextResponse.succeeded(): Boolean = status in 200..299

    private fun ClientResponse.succeeded(): Boolean = status in 200..299

    private fun failed(method: Method, path: String, response: TextResponse): Nothing =
        throw ApiCallFailed(response.status, method.name, path, response.body)

    /**
     * The body decoded, or a refusal naming the call it came back on.
     *
     * A status this endpoint declared is not a promise about what a proxy in front
     * of it sends: an HTML 404 and a plain-text 502 both arrive here, and a bare
     * codec exception would carry neither the status, the path, nor the bytes that
     * would explain it. [raw] is whatever the codec was handed — a whole body, or
     * one frame of a stream.
     */
    private fun <T> BodyCodec<T>.decoded(raw: String, method: Method, path: String, status: Int): T =
        try {
            decodeFromString(raw)
        } catch (failure: Exception) {
            throw ApiCallFailed(status, method.name, path, raw, failure)
        }

    /** A failed streaming response's body is the one time it is small enough to read whole. */
    private fun drain(response: ClientResponse): String = response.text()

    private fun failedStream(method: Method, path: String, response: ClientResponse): Nothing =
        throw ApiCallFailed(response.status, method.name, path, drain(response))

    /**
     * The exchange, waited for.
     *
     * A transport answers with a `CompletionStage` because that is the one shape
     * every transport can offer: an asynchronous client serves a blocking caller
     * with a join, and a blocking one cannot serve an asynchronous caller without
     * a thread per call. This is that join.
     *
     * A `CompletionException` is unwrapped on the way out, so what a caller catches
     * is the failure the transport actually raised — an `IOException`, a timeout —
     * rather than a wrapper the choice of transport put around it.
     */
    private fun exchange(request: ClientRequest): ClientResponse =
        try {
            transport.send(request).toCompletableFuture().join()
        } catch (failed: CompletionException) {
            throw failed.cause ?: failed
        }

    private fun text(request: ClientRequest): TextResponse =
        exchange(request).let { TextResponse(it, it.text()) }

    private fun stream(request: ClientRequest): ClientResponse = exchange(request)

    private val proposedTransferCodec: BodyCodec<ProposedTransfer> = codecs.codec(typeOf<ProposedTransfer>())
    private val decisionCodec: BodyCodec<Decision> = codecs.codec(typeOf<Decision>())

    /**
     * Decide, once and for good, whether a proposed transfer may move
     *
     * `POST /screen`
     */
    fun screen(body: ProposedTransfer): Decision {
        val response = text(request(Method.POST, "/screen", body = ClientRequest.Body.Text(proposedTransferCodec.encodeToString(body)), contentType = "application/json"))
        if (!response.succeeded()) failed(Method.POST, "/screen", response)
        return decisionCodec.decoded(response.body, Method.POST, "/screen", response.status)
    }
}
