addSbtPlugin("org.scalameta"   % "sbt-scalafmt"        % "2.6.2")
addSbtPlugin("org.typelevel"   % "sbt-tpolecat"        % "0.5.7")
addSbtPlugin("com.github.sbt" %% "sbt-native-packager" % "1.11.7")
addSbtPlugin("org.scoverage"  %% "sbt-scoverage"       % "2.4.4")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s"       % "1.1.1")
